### ISSUE TITLE
E-mails

### ISSUE THREAD

**Issue by fabiocolella** [smartexagro/smartexagro.github.io#10]
Contratar serviço e criar contas de redirecionamento de e-mail

**Comment by fabiocolella** [comment]
CHECAR: https://www.registrocom.com/redirecionamento_dominio/

**Comment by smartexagro** [comment]
Resolvido pelo Mailgun.com
Aguardando o Roberto liberar o serviço para configuração

**Comment by hansbonini** [comment]
Resolvido pelo http://mailgun.com
Aguardando liberação do serviço pelo Roberto para configuração.
